### PR TITLE
Add consistentency to the filenames and module names

### PR DESCRIPTION
**Pull request by mohnish**
- Change the gem namespace from `Planout` to `PlanOut`
- Change `LongScale` to `LONG_SCALE` [[reference]](https://github.com/bbatsov/ruby-style-guide#screaming-snake-case)
- Fix Travis CI build errors
- Move the classes into files that match the python implementation

References:
- http://guides.rubygems.org/name-your-gem/
- https://github.com/bbatsov/ruby-style-guide#snake-case-files
- Travis Status: https://travis-ci.org/mohnish/planout (This should be available on https://github.com/facebook/planout once merged!)

### CODE REVIEW

**Comment by mohnish** [comment]
Moved the `Operator` and `SimpleOperator` into one file

**Comment by eytan** [comment]
Thanks for all of your help @mohnish!

**Comment by mohnish** [comment]
my pleasure :)

**Comment by eytan** [comment]
Hey @mohnish, if I wanted to have a Travis CI build status for the Python PlanOut package, how would that work?  I noticed that there is a Ruby-specific .travis.yml file in the root directory of the PlanOut repository and was wondering if that needs to be there or could be in alpha/ruby/.

**Comment by mohnish** [comment]
@eytan looks like travis doesn't support multiple languages yet. also, the `.travis.yml` file only needs to be inside the root of the application in order to allow travis to pick the repository up for building. imo travis could be used to build the python version and maybe another CI could be used to build the ruby version (https://drone.io/ looks alright). curious to know what you think. :-)

**Pull request merged**
