### PR TITLE
Extend planout interpreter for python

### PR DESCRIPTION
**Pull request by irvifa**
Extend planout interpreter for python to have sum and sqrt.
This is related to this issues:
1. [Extending the Interpreter to Use Sqrt and Exp Operator.](https://github.com/facebook/planout/issues/147)
2. [Example for online evaluation.](https://github.com/facebook/Ax/issues/77)

### CODE REVIEW

**Comment by irvifa** [comment]
The test seems to be failed since it can't clone git submodules for the other clients, e.g. golang etc.

**Comment by irvifa** [comment]
@sdsingh hmm any style guidelines that can be imported to ide? I tried to run the pylint check and there’s no error..

**Comment by sdsingh** [comment]
Hmm, I think the PEP guideline here is fairly clear: https://www.python.org/dev/peps/pep-0008/#imports. Importing multiple modules from a package is fine, and we do this throughout the repo, so I think we should keep this file consistent.

**Comment by irvifa** [comment]
@sdsingh Hi 👋 Sorry for my delay. I've tried to fix the code styling, have you already noticed on what causing error on the travis?

**Comment by sdsingh** [comment]
Thank you!

I saw the Travis issue, I haven't been able to debug it unfortunately. I'm happy to accept this change, though, I'm certain this issue is not introducing the test failure.

**Comment by irvifa** [comment]
@sdsingh Thanks! Anything that need to be done before that?

**Comment by irvifa** [comment]
@sdsingh I fixed the travis build..

**Comment by sdsingh** [comment]
Wow, @irvifa, thanks for these fixes! Appreciate it!

**Pull request merged**
