### PR TITLE
Correct the max segment value in Namespace.get_segment

### PR DESCRIPTION
**Pull request by eric239**
This is fix for issue #41

### CODE REVIEW

**Comment by eytan** [comment]
Thanks for this.  As a heads up, it is likely that the interface / setup for namespaces will change quite a bit in the next several weeks.  I wrote it as a sort of demonstration of the concept of namespaces, but it isn't intended for use in production.  Vimeo and URX have been doing development on production-ready versions of namespaces in their ports of PlanOut to PHP and Go, and once we figure out a nice, standardized set of functions for managing namespaces, I will update the Python reference to reflect that.

**Comment by eric239** [comment]
Hello,

Firstly, thanks for opensourcing the great product.

We (Glassdoor) have finished porting PlanOut into Java (I know, boring old
java but still pretty widely used :-) ) and hope to contribute the code
back once it goes through some internal trials and our legal blesses the
opensourcing.

As far as namespaces go, we took the approach of expressing the name,
segments, experiments definitions, and experiments sequencing in the form
of a config file (yaml + PlanOut DSL) rather than expect developers to
subclass to setup namespaces and experiments.

Do you have a set of guidelines a good port should follow?
We'll look at the existing PHP/Ruby/Go ports as well of course.

Best,
Ernest (aka eric239)

**Comment by eytan** [comment]
Awesome!  I plan to write up a doc soon on contributing ports and how to
set up the READMEs, etc.

Yeah, we do something similar at Facebook -- the classes are really just
for getting folks up and running (see
https://facebook.github.io/planout/blog/planout-language.html).  We
essentially have a database which maps (namespace, segment) pairs to
experiments, and then have a datastore which, for each experiment,  stores
the script and associated metadata (including e.g., how/where to log the
data, and how exposure logs should be cached).

Also, if you have any questions about open sourcing Glassdoor's
implementation, have any additional questions, feel free to drop me an
email at my first name at fb.com.

**Comment by eytan** [comment]
Hi @eric239 -- any updates?  It seems that this "boring old java" port could be really useful to a lot of people.  Since your PR, a number of folks outside of Facebook have asked about PlanOut for Java, and I am currently working on an experiment that involves client-side randomization (on Android), so having a Java-based PlanOut interpreter would be pretty handy right about now...

FWIW, Vimeo's port of PlanOut to PHP just hit 1.0.  Their README.md does a pretty good job of outlining the commonalities and differences between the Python reference implementation and theirs: https://github.com/vimeo/ABLincoln

I'd be happy to review any code, and feel free to email me if you have any questions / concerns.

**Comment by eric239** [comment]
Hi, it's been on the back burner due to me being swamped, but I really want
to keep my word and the idea was approved by our legal and management. I
will get back to you around the weekend with a list of questions and
hopefully initial code drop.

Regards,
Ernest

**Comment by eytan** [comment]
Awesome, looking forward to it!

**Comment by eric239** [comment]
The conversation moved to issue #52

**Pull request merged**
