### PR TITLE
Early return in Sample

### PR DESCRIPTION
**Pull request by rawls238**
@eytan

### CODE REVIEW

**Comment by rawls238** [comment]
relevant PR in the JS implementation: https://github.com/HubSpot/PlanOut.js/pull/22

@eytan should we have some sort of migration flag here similar to the one in the JS implementation?

**Comment by rawls238** [comment]
@eytan any qualms against merging this and releasing v0.6 to pypi?

**Comment by eytan** [comment]
Are we also going to update Namespace to have a flag to enable `FastSample`?

**Comment by rawls238** [comment]
Yea added a flag in `Namespace` and I just ran the following script to verify behavior:

```python
from planout.experiment import SimpleExperiment
from planout.ops.random import *

class Exp1(SimpleExperiment):
  def assign(self, params, userid):
    params.test = Sample(
      choices=['a', 'b', 'c'],
      unit=userid)

with open('results2', 'wb+') as f:
  for i in range(50):
    a = Exp1(userid=i)
    f.write(','.join(a.get('test')))
```

which both on master and on this branch produces the following results ```a,c,bb,a,ca,c,bc,b,ac,b,ab,c,ab,c,aa,b,cc,a,ba,c,bb,a,cb,c,ab,c,ab,c,aa,b,cc,a,bb,c,ab,a,cc,b,aa,b,cc,a,bc,a,bb,c,ab,c,ab,a,cb,c,aa,b,cc,a,bc,b,ab,c,ac,a,bb,a,cb,a,ca,b,ca,c,ba,c,bb,c,ab,c,ab,a,cc,b,ab,c,ac,b,aa,c,bb,a,cb,c,ac,b,ab,a,cb,a,ca,c,ba,c,b```

**Pull request merged**
